/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as SuccessRouteImport } from './routes/success'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AiRouteImport } from './routes/ai'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PlaygroundLayoutRouteImport } from './routes/playground/_layout'
import { Route as PlaygroundLayoutIndexRouteImport } from './routes/playground/_layout/index'
import { Route as ApiRpcSplatRouteImport } from './routes/api/rpc/$'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiAiSplatRouteImport } from './routes/api/ai/$'

const PlaygroundRouteImport = createFileRoute('/playground')()

const PlaygroundRoute = PlaygroundRouteImport.update({
  id: '/playground',
  path: '/playground',
  getParentRoute: () => rootRouteImport,
} as any)
const SuccessRoute = SuccessRouteImport.update({
  id: '/success',
  path: '/success',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AiRoute = AiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaygroundLayoutRoute = PlaygroundLayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => PlaygroundRoute,
} as any)
const PlaygroundLayoutIndexRoute = PlaygroundLayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PlaygroundLayoutRoute,
} as any)
const ApiRpcSplatRoute = ApiRpcSplatRouteImport.update({
  id: '/api/rpc/$',
  path: '/api/rpc/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiSplatRoute = ApiAiSplatRouteImport.update({
  id: '/api/ai/$',
  path: '/api/ai/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai': typeof AiRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/success': typeof SuccessRoute
  '/playground': typeof PlaygroundLayoutRouteWithChildren
  '/api/ai/$': typeof ApiAiSplatRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
  '/playground/': typeof PlaygroundLayoutIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai': typeof AiRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/success': typeof SuccessRoute
  '/playground': typeof PlaygroundLayoutIndexRoute
  '/api/ai/$': typeof ApiAiSplatRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ai': typeof AiRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/success': typeof SuccessRoute
  '/playground': typeof PlaygroundRouteWithChildren
  '/playground/_layout': typeof PlaygroundLayoutRouteWithChildren
  '/api/ai/$': typeof ApiAiSplatRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
  '/playground/_layout/': typeof PlaygroundLayoutIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai'
    | '/dashboard'
    | '/login'
    | '/success'
    | '/playground'
    | '/api/ai/$'
    | '/api/auth/$'
    | '/api/rpc/$'
    | '/playground/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai'
    | '/dashboard'
    | '/login'
    | '/success'
    | '/playground'
    | '/api/ai/$'
    | '/api/auth/$'
    | '/api/rpc/$'
  id:
    | '__root__'
    | '/'
    | '/ai'
    | '/dashboard'
    | '/login'
    | '/success'
    | '/playground'
    | '/playground/_layout'
    | '/api/ai/$'
    | '/api/auth/$'
    | '/api/rpc/$'
    | '/playground/_layout/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AiRoute: typeof AiRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  SuccessRoute: typeof SuccessRoute
  PlaygroundRoute: typeof PlaygroundRouteWithChildren
  ApiAiSplatRoute: typeof ApiAiSplatRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiRpcSplatRoute: typeof ApiRpcSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/playground': {
      id: '/playground'
      path: '/playground'
      fullPath: '/playground'
      preLoaderRoute: typeof PlaygroundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/success': {
      id: '/success'
      path: '/success'
      fullPath: '/success'
      preLoaderRoute: typeof SuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai': {
      id: '/ai'
      path: '/ai'
      fullPath: '/ai'
      preLoaderRoute: typeof AiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playground/_layout': {
      id: '/playground/_layout'
      path: '/playground'
      fullPath: '/playground'
      preLoaderRoute: typeof PlaygroundLayoutRouteImport
      parentRoute: typeof PlaygroundRoute
    }
    '/playground/_layout/': {
      id: '/playground/_layout/'
      path: '/'
      fullPath: '/playground/'
      preLoaderRoute: typeof PlaygroundLayoutIndexRouteImport
      parentRoute: typeof PlaygroundLayoutRoute
    }
    '/api/rpc/$': {
      id: '/api/rpc/$'
      path: '/api/rpc/$'
      fullPath: '/api/rpc/$'
      preLoaderRoute: typeof ApiRpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai/$': {
      id: '/api/ai/$'
      path: '/api/ai/$'
      fullPath: '/api/ai/$'
      preLoaderRoute: typeof ApiAiSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface PlaygroundLayoutRouteChildren {
  PlaygroundLayoutIndexRoute: typeof PlaygroundLayoutIndexRoute
}

const PlaygroundLayoutRouteChildren: PlaygroundLayoutRouteChildren = {
  PlaygroundLayoutIndexRoute: PlaygroundLayoutIndexRoute,
}

const PlaygroundLayoutRouteWithChildren =
  PlaygroundLayoutRoute._addFileChildren(PlaygroundLayoutRouteChildren)

interface PlaygroundRouteChildren {
  PlaygroundLayoutRoute: typeof PlaygroundLayoutRouteWithChildren
}

const PlaygroundRouteChildren: PlaygroundRouteChildren = {
  PlaygroundLayoutRoute: PlaygroundLayoutRouteWithChildren,
}

const PlaygroundRouteWithChildren = PlaygroundRoute._addFileChildren(
  PlaygroundRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AiRoute: AiRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  SuccessRoute: SuccessRoute,
  PlaygroundRoute: PlaygroundRouteWithChildren,
  ApiAiSplatRoute: ApiAiSplatRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiRpcSplatRoute: ApiRpcSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
